In [1]:
import torch

In [2]:
inputs=torch.tensor(
    [
     [0.43,0.15,0.89],#your
     [0.55,0.87,0.66],#journey
     [0.57,0.85,0.64],#starts
     [0.22,0.58,0.33],#with
     [0.77,0.25,0.10],#one
     [0.05,0.80,0.55],#step
    ]
)

In [3]:
w_q=torch.nn.Linear(inputs.shape[1],2,bias=False)
print(w_q)
w_k=torch.nn.Linear(inputs.shape[1],2,bias=False)
w_v=torch.nn.Linear(inputs.shape[1],2,bias=False)

Linear(in_features=3, out_features=2, bias=False)


In [4]:
queries=w_q(inputs)
keys=w_k(inputs)
values=w_v(inputs)

print(queries)

tensor([[-0.1654,  0.2226],
        [-0.0417,  0.5664],
        [-0.0454,  0.5493],
        [ 0.0107,  0.3694],
        [-0.0993,  0.0858],
        [ 0.0432,  0.5531]], grad_fn=<MmBackward0>)


In [5]:
attn_score=queries@keys.T
print(attn_score)

tensor([[-0.0588, -0.1890, -0.1850, -0.1207, -0.0614, -0.1651],
        [-0.1896, -0.4089, -0.4014, -0.2481, -0.1534, -0.3344],
        [-0.1833, -0.3974, -0.3901, -0.2414, -0.1488, -0.3254],
        [-0.1276, -0.2595, -0.2549, -0.1559, -0.0997, -0.2095],
        [-0.0189, -0.0796, -0.0778, -0.0520, -0.0239, -0.0717],
        [-0.1940, -0.3834, -0.3766, -0.2293, -0.1491, -0.3075]],
       grad_fn=<MmBackward0>)


In [6]:
attn_weight=torch.softmax(attn_score/keys.shape[1]**0.5,dim=1)
print(attn_weight)

tensor([[0.1751, 0.1597, 0.1602, 0.1676, 0.1748, 0.1625],
        [0.1784, 0.1528, 0.1536, 0.1712, 0.1830, 0.1610],
        [0.1782, 0.1531, 0.1539, 0.1710, 0.1826, 0.1612],
        [0.1733, 0.1579, 0.1584, 0.1699, 0.1768, 0.1636],
        [0.1708, 0.1637, 0.1639, 0.1669, 0.1702, 0.1646],
        [0.1759, 0.1539, 0.1546, 0.1716, 0.1816, 0.1624]],
       grad_fn=<SoftmaxBackward0>)


In [7]:
#use pytorch tril function to diagonalize
context_length=inputs.shape[0]
mask1=torch.tril(torch.ones(context_length,context_length))
print(mask1)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [8]:
#use element wise multiplication not matrix
masked_attn_score=attn_weight*mask1
print(masked_attn_score)

#but this attention score is not fully masked or optimal becaus the softmax normalization adds influence on its from the previous attn score so use upper negative infinity mask instead of zero

tensor([[0.1751, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1784, 0.1528, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1782, 0.1531, 0.1539, 0.0000, 0.0000, 0.0000],
        [0.1733, 0.1579, 0.1584, 0.1699, 0.0000, 0.0000],
        [0.1708, 0.1637, 0.1639, 0.1669, 0.1702, 0.0000],
        [0.1759, 0.1539, 0.1546, 0.1716, 0.1816, 0.1624]],
       grad_fn=<MulBackward0>)


In [9]:
#normalize the masked attention score  to sum up 1 in each row to get masked attn weight
row_sum=masked_attn_score.sum(dim=1,keepdim=True)
print(row_sum)
masked_attn_weight=masked_attn_score/row_sum
print(masked_attn_weight)

tensor([[0.1751],
        [0.3312],
        [0.4853],
        [0.6596],
        [0.8354],
        [1.0000]], grad_fn=<SumBackward1>)
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5387, 0.4613, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3672, 0.3156, 0.3172, 0.0000, 0.0000, 0.0000],
        [0.2628, 0.2394, 0.2402, 0.2576, 0.0000, 0.0000],
        [0.2045, 0.1959, 0.1961, 0.1997, 0.2038, 0.0000],
        [0.1759, 0.1539, 0.1546, 0.1716, 0.1816, 0.1624]],
       grad_fn=<DivBackward0>)


In [10]:
masked_context_vectore=masked_attn_weight@values
print(masked_context_vectore)

tensor([[ 0.2130, -0.6795],
        [ 0.3920, -0.8111],
        [ 0.4560, -0.8569],
        [ 0.4368, -0.7743],
        [ 0.4082, -0.7247],
        [ 0.4111, -0.7052]], grad_fn=<MmBackward0>)


# Negative infinity masking to avoid any influence of future attention

In [11]:
print(attn_score)

tensor([[-0.0588, -0.1890, -0.1850, -0.1207, -0.0614, -0.1651],
        [-0.1896, -0.4089, -0.4014, -0.2481, -0.1534, -0.3344],
        [-0.1833, -0.3974, -0.3901, -0.2414, -0.1488, -0.3254],
        [-0.1276, -0.2595, -0.2549, -0.1559, -0.0997, -0.2095],
        [-0.0189, -0.0796, -0.0778, -0.0520, -0.0239, -0.0717],
        [-0.1940, -0.3834, -0.3766, -0.2293, -0.1491, -0.3075]],
       grad_fn=<MmBackward0>)


In [12]:
mask=torch.triu(torch.ones(context_length,context_length),diagonal=1)
print(mask)
masked=attn_score.masked_fill(mask.bool(),-torch.inf)
print(masked)

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[-0.0588,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.1896, -0.4089,    -inf,    -inf,    -inf,    -inf],
        [-0.1833, -0.3974, -0.3901,    -inf,    -inf,    -inf],
        [-0.1276, -0.2595, -0.2549, -0.1559,    -inf,    -inf],
        [-0.0189, -0.0796, -0.0778, -0.0520, -0.0239,    -inf],
        [-0.1940, -0.3834, -0.3766, -0.2293, -0.1491, -0.3075]],
       grad_fn=<MaskedFillBackward0>)


In [13]:
masked_attn_weight=torch.softmax(masked/keys.shape[1],dim=1)
print(masked_attn_weight)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5274, 0.4726, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3571, 0.3209, 0.3220, 0.0000, 0.0000, 0.0000],
        [0.2590, 0.2425, 0.2431, 0.2554, 0.0000, 0.0000],
        [0.2032, 0.1971, 0.1973, 0.1998, 0.2027, 0.0000],
        [0.1732, 0.1576, 0.1581, 0.1702, 0.1772, 0.1637]],
       grad_fn=<SoftmaxBackward0>)


# Masking additional attention weight with Dropout

In [14]:
torch.manual_seed(123)
dropout=torch.nn.Dropout(0.5)
print(dropout)
ones=torch.ones(6,6)
print(ones)
print(dropout(ones))

Dropout(p=0.5, inplace=False)
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])


In [15]:
attn_dropout=dropout(attn_weight)
print(attn_dropout)

tensor([[0.3503, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3072, 0.0000, 0.3661, 0.3221],
        [0.0000, 0.3063, 0.3079, 0.3420, 0.3652, 0.3223],
        [0.0000, 0.0000, 0.3169, 0.3398, 0.0000, 0.3272],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.3404, 0.3291],
        [0.3519, 0.3078, 0.0000, 0.3432, 0.3632, 0.3247]],
       grad_fn=<MulBackward0>)


# Causal attention Class with Batches

In [16]:
batch=torch.stack((inputs,inputs),dim=0)
print(batch)
print(batch.shape)

tensor([[[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]],

        [[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]])
torch.Size([2, 6, 3])


In [17]:
print(batch.transpose(1,2))#change row(1) with colmn(2)

tensor([[[0.4300, 0.5500, 0.5700, 0.2200, 0.7700, 0.0500],
         [0.1500, 0.8700, 0.8500, 0.5800, 0.2500, 0.8000],
         [0.8900, 0.6600, 0.6400, 0.3300, 0.1000, 0.5500]],

        [[0.4300, 0.5500, 0.5700, 0.2200, 0.7700, 0.0500],
         [0.1500, 0.8700, 0.8500, 0.5800, 0.2500, 0.8000],
         [0.8900, 0.6600, 0.6400, 0.3300, 0.1000, 0.5500]]])


In [18]:
class Causal_Attention(torch.nn.Module):
    def __init__(self,in_d,out_d,context_length,dropout_percent):
        super().__init__()
        self.w_q=torch.nn.Linear(in_d,out_d)
        self.w_k=torch.nn.Linear(in_d,out_d)
        self.w_v=torch.nn.Linear(in_d,out_d)
        self.dropout=torch.nn.Dropout(dropout_percent)
        self.register_buffer('mask',torch.triu(torch.ones(context_length,context_length),diagonal=1))

    
    def forward(self,input_embedding):
        
        b,num_token,d_in=input_embedding.shape
        queries=self.w_q(input_embedding)
        keys=self.w_k(input_embedding)
        values=self.w_v(input_embedding)

        print(keys.shape[-1])

        attn_score=queries@keys.transpose(1,2)

        attn_score.masked_fill_(self.mask.bool()[:num_token, :num_token],-torch.inf)
        
        print('attn_score',attn_score)
        attn_weight=torch.softmax(attn_score/keys.shape[-1]**0.5,dim=-1)
        print('attn_weight',attn_weight)
        attn_weight=self.dropout(attn_weight)

        masked_context_vectore=attn_weight@values
        return masked_context_vectore

        
        

        
        


In [19]:
in_d,out_d=3,3
print(in_d)

3


In [20]:
torch.manual_seed(123)
context_length=batch.shape[1]
print(context_length)
ca=Causal_Attention(in_d,out_d,context_length,0.0)
print(ca)

ca.forward(batch)


6
Causal_Attention(
  (w_q): Linear(in_features=3, out_features=3, bias=True)
  (w_k): Linear(in_features=3, out_features=3, bias=True)
  (w_v): Linear(in_features=3, out_features=3, bias=True)
  (dropout): Dropout(p=0.0, inplace=False)
)
3
attn_score tensor([[[-0.2173,    -inf,    -inf,    -inf,    -inf,    -inf],
         [-0.6607, -0.5641,    -inf,    -inf,    -inf,    -inf],
         [-0.6516, -0.5573, -0.5477,    -inf,    -inf,    -inf],
         [-0.3954, -0.3047, -0.3003, -0.2375,    -inf,    -inf],
         [-0.2972, -0.2652, -0.2612, -0.2145, -0.1605,    -inf],
         [-0.5065, -0.3916, -0.3856, -0.3170, -0.2411, -0.3807]],

        [[-0.2173,    -inf,    -inf,    -inf,    -inf,    -inf],
         [-0.6607, -0.5641,    -inf,    -inf,    -inf,    -inf],
         [-0.6516, -0.5573, -0.5477,    -inf,    -inf,    -inf],
         [-0.3954, -0.3047, -0.3003, -0.2375,    -inf,    -inf],
         [-0.2972, -0.2652, -0.2612, -0.2145, -0.1605,    -inf],
         [-0.5065, -0.3916, -0.

tensor([[[-0.0755,  0.2528,  0.4010],
         [ 0.0065,  0.5118,  0.5036],
         [ 0.0316,  0.5984,  0.5364],
         [ 0.0758,  0.6148,  0.4682],
         [ 0.0707,  0.6636,  0.4533],
         [ 0.0984,  0.6533,  0.4289]],

        [[-0.0755,  0.2528,  0.4010],
         [ 0.0065,  0.5118,  0.5036],
         [ 0.0316,  0.5984,  0.5364],
         [ 0.0758,  0.6148,  0.4682],
         [ 0.0707,  0.6636,  0.4533],
         [ 0.0984,  0.6533,  0.4289]]], grad_fn=<UnsafeViewBackward0>)

# Multi head attention wrapper class

In [21]:
class MultiHeadAttentionWrapper(torch.nn.Module):

    def __init__(self,in_d,out_d,context_length,dropout_percent,num_head):

        super().__init__()
        self.heads=torch.nn.ModuleList([Causal_Attention(in_d,out_d,context_length,dropout_percent) for _ in range(num_head)])
        print('self head',self.heads)
    def forward(self,inputs):
        return torch.cat([head(inputs) for head in self.heads],dim=-1)

In [22]:
torch.manual_seed(123)
context_length=batch.shape[1]
print(context_length)
mha=MultiHeadAttentionWrapper(in_d,out_d,context_length,0.0,num_head=2)

context_vec=mha(batch)
print('context_veccccccccc',context_vec)




6
self head ModuleList(
  (0-1): 2 x Causal_Attention(
    (w_q): Linear(in_features=3, out_features=3, bias=True)
    (w_k): Linear(in_features=3, out_features=3, bias=True)
    (w_v): Linear(in_features=3, out_features=3, bias=True)
    (dropout): Dropout(p=0.0, inplace=False)
  )
)
3
attn_score tensor([[[-0.2173,    -inf,    -inf,    -inf,    -inf,    -inf],
         [-0.6607, -0.5641,    -inf,    -inf,    -inf,    -inf],
         [-0.6516, -0.5573, -0.5477,    -inf,    -inf,    -inf],
         [-0.3954, -0.3047, -0.3003, -0.2375,    -inf,    -inf],
         [-0.2972, -0.2652, -0.2612, -0.2145, -0.1605,    -inf],
         [-0.5065, -0.3916, -0.3856, -0.3170, -0.2411, -0.3807]],

        [[-0.2173,    -inf,    -inf,    -inf,    -inf,    -inf],
         [-0.6607, -0.5641,    -inf,    -inf,    -inf,    -inf],
         [-0.6516, -0.5573, -0.5477,    -inf,    -inf,    -inf],
         [-0.3954, -0.3047, -0.3003, -0.2375,    -inf,    -inf],
         [-0.2972, -0.2652, -0.2612, -0.2145, -0.

# MultiHead attention with weight splits

In [91]:
class MultiHeadAttention(torch.nn.Module):
    def __init__(self,d_in,d_out,context_length,num_heads,dropout_percent):
        super().__init__()
        assert (d_out%num_heads==0)

        self.d_out=d_out
        self.num_heads=num_heads
        self.head_dim=self.d_out//self.num_heads
        self.wk=torch.nn.Linear(d_in,d_out)
        self.wq=torch.nn.Linear(d_in,d_out)
        self.wv=torch.nn.Linear(d_in,d_out)
        self.out_proj=torch.nn.Linear(d_out,d_out)
        self.dropout=torch.nn.Dropout(dropout_percent)
        self.register_buffer('mask',torch.triu(torch.ones(context_length,context_length),diagonal=1))

    def forward(self,batch):
        b,num_token,d_in=batch.shape
        keys=self.wk(batch)# shape: (b,num_token,d_out)
        queries=self.wq(batch)
        values=self.wv(batch)
        
        #implicitly split the matrix by adding 'num_heads' dimension
        #(b,num_token,d_out)--->(b,num_token,num_head,head_dim)

        keys=keys.view(b,num_token,self.num_heads,self.head_dim)
        queries=queries.view(b,num_token,self.num_heads,self.head_dim)
        values=values.view(b,num_token,self.num_heads,self.head_dim)

        #transpose: (b,num_token,num_head,head_dim)---->(b,num_head,num_token,head_dim)

        keys=keys.transpose(1,2)
        queries=queries.transpose(1,2)
        values=values.transpose(1,2)

      
        
        #compute self attention with causal mask
        attn_score=queries@keys.transpose(2,3) #dot product for each head
        mask_bool=self.mask.bool()[:num_token,:num_token]
   
        attn_score.masked_fill_(mask_bool,-torch.inf)
  
        attn_weight=torch.softmax(attn_score/keys.shape[-1]**0.5,dim=-1)
        attn_weight=self.dropout(attn_weight)

        #shape (b,num_head,num_token,head_dim)---->(b,num_token,num_head,head_dim)
        context_vec=(attn_weight@values).transpose(1,2)

        #combine heads, where self.d_out=self.head_num*self.head_dim
        context_vec=context_vec.contiguous().view(b,num_token,self.d_out)

        

        print(context_vec)

       

        


       

        

In [92]:
MHA=MultiHeadAttention(3,6,6,2,0.5)

print(batch.shape)
MHA(batch)

torch.Size([2, 6, 3])
tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000, -0.7733,  1.3123, -1.0517],
         [ 0.0093, -0.4044, -0.0967, -0.5161,  0.8724, -0.7013],
         [-0.0227, -0.5614, -0.1087, -0.2413,  0.2450, -0.2055],
         [-0.0786, -0.4241, -0.2329, -0.3155,  0.5353, -0.4302],
         [-0.0480, -0.4746, -0.2006, -0.1963,  0.3463, -0.2713]],

        [[-0.1237, -0.9209, -0.1513, -0.9943,  1.0095, -0.8469],
         [-0.0628, -0.4680, -0.0769, -0.2872,  0.8188, -0.6376],
         [-0.0209, -1.1272, -0.2364,  0.0000,  0.0000,  0.0000],
         [ 0.0074, -0.3185, -0.0762, -0.2956,  0.5209, -0.4081],
         [-0.0538, -0.2397, -0.2026, -0.1636,  0.5575, -0.4257],
         [-0.0306, -0.2263, -0.1261, -0.2258,  0.7198, -0.5535]]],
       grad_fn=<ViewBackward0>)
