In [1]:
import torch

In [2]:
inputs=torch.tensor(
    [
     [0.43,0.15,0.89],#your
     [0.55,0.87,0.66],#journey
     [0.57,0.85,0.64],#starts
     [0.22,0.58,0.33],#with
     [0.77,0.25,0.10],#one
     [0.05,0.80,0.55],#step
     ]
)

In [3]:
#the second input token serves as the query
query=inputs[1]
print(inputs.shape)
attn_scores_2=torch.empty(inputs.shape[0])

for i,x_i in enumerate(inputs):
    attn_scores_2[i]=torch.dot(x_i,query) #dot product

print(attn_scores_2)



torch.Size([6, 3])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


# Normalization
the main goal of normalization is to obtain attention weigt that sums upto 1.

In [4]:
attn_weight_2_tmp=attn_scores_2/attn_scores_2.sum()#normalized

print('Attention weight:', attn_weight_2_tmp)
print('Sum:',attn_weight_2_tmp.sum())

Attention weight: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


In [5]:
#in practice we use soft max for normalizations
#the attention weight is always positive 
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive=softmax_naive(attn_scores_2)

print('Attention weight:', attn_weights_2_naive)
print('Sum:',attn_weights_2_naive.sum())

Attention weight: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [6]:
attn_weights_2=torch.softmax(attn_scores_2,dim=0)
print('Attention weight:', attn_weights_2)
print('Sum:',attn_weights_2.sum())

Attention weight: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


# Context Vectore
to get context vectore multiply eah corresponding attention weight with its corresponding input vectore and sum them

In [ ]:
#to get context vectore multiply eah corresponding attention weight with its corresponding input vectore and sum them

query=inputs[1]
context_vector_2=torch.zeros(query.shape)#context vector of input 2
print(context_vector_2)
for i,inpt in enumerate(inputs):
    context_vector_2+=inpt*attn_weights_2[i]#scale each input with their attn score
print(context_vector_2)


tensor([0., 0., 0.])
tensor([0.4419, 0.6515, 0.5683])


In [ ]:
attn_scores=torch.zeros([6,6])
print(attn_scores)

for i,inpt_i in enumerate(inputs):
    for j,input_j in enumerate(inputs):
        attn_scores[i,j]=torch.dot(inpt_i,input_j)
print(attn_scores)

#but this approach is computationally costy so use matrix transpose

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [23]:
attn_scores=inputs@inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [42]:
#now lets normalize the attention matrix
attn_weights=torch.softmax(attn_scores,dim=-1)





In [44]:
all_context_vec=attn_weights@inputs
print(all_context_vec)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
