In [1]:
import torch

In [2]:
input_ids=torch.tensor([2,3,5,1])

In [8]:
#for simplicity use vocab size 6 and embedding size 3

vocab_size=6
output_dim=3

embedding_layers=torch.nn.Embedding(vocab_size,output_dim)

In [9]:
print(embedding_layers.weight)

Parameter containing:
tensor([[ 2.2253,  1.5591,  0.0472],
        [ 0.3287,  0.0109,  0.0095],
        [-0.3663,  0.7540,  0.2065],
        [ 1.2211, -0.4279, -1.3518],
        [ 1.6022, -0.1259,  0.7456],
        [ 1.6949,  0.1223,  1.5113]], requires_grad=True)


In [ ]:
print(embedding_layers(torch.tensor([3])))

tensor([[ 1.2211, -0.4279, -1.3518],
        [ 0.3287,  0.0109,  0.0095]], grad_fn=<EmbeddingBackward0>)


In [13]:
print(embedding_layers(input_ids))

tensor([[-0.3663,  0.7540,  0.2065],
        [ 1.2211, -0.4279, -1.3518],
        [ 1.6949,  0.1223,  1.5113],
        [ 0.3287,  0.0109,  0.0095]], grad_fn=<EmbeddingBackward0>)
